### PR TITLE
use Redux in React components

### PR DESCRIPTION
**Pull request by Fene-87**
In this project milestone, I use a redux store to display books.
- I connect the store to the index.js file.
- I define a slice that contains all my books.
- I display the books received from the slice in a different component.
- I implement event handlers that: 
                                                        - Adds a book to the books array.
                                                        -Removes a book from the books array.
                                                        -Checks for status in the categories page.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
Hi @Fene-87, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct readme. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in a student's repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fene-87** [comment]
Readme updated

**Review by Davidosky007 — APPROVED** [review]
Hi @Fene-87 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fene-87** [comment]
Thank you for your time and effort

**Pull request merged**
